version: '3.3'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_app_network

  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend_app_network

volumes:
  postgres_data:

networks:
  backend_app_network:
    driver: bridge
